name: Build and deploy Node.js app to Azure Web App - Health-RiskCalculator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install
        working-directory: server  # Set the correct working directory

      - name: Build (if applicable)
        run: npm run build --if-present
        working-directory: server  # Set the correct working directory

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: server  # Set the correct working directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Health-RiskCalculator'
          slot-name: 'Production'
          package: server  # Set the correct working directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
